/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_gestionagents (void);
GtkWidget* create_accueil (void);
GtkWidget* create_modifiersupprimer (void);
GtkWidget* create_reclamations (void);
GtkWidget* create_gestionfidelites (void);
GtkWidget* create_msgaj (void);
GtkWidget* create_msgsupp (void);
GtkWidget* create_msgmod (void);
